export const SET_SLIDES = 'SET_SLIDES';
export const SET_SLIDE_NUMBER = 'SET_SLIDE_NUMBER';
export const CHANGE_SLIDE = 'CHANGE_SLIDE';
export const GO_TO_SLIDE = 'GO_TO_SLIDE';
export const CHANGE_SLIDER_MODE = 'CHANGE_SLIDER_MODE';
